name: predict-daily

on:
  schedule:
    - cron: "0 23 * * *"     # 08:00 KST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      SA_PATH:  ${{ github.workspace }}/sa.json
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth pandas numpy holidays

      - name: Write SA key
        run: |
          printf '%s' "${{ secrets.GDRIVE_SA_JSON }}" > "${SA_PATH}"

      - name: Predict & write
        env:
          # 필요 월이 바뀌면 아래 값만 바꿔도 됩니다.
          PYTHONUNBUFFERED: "1"
        run: |
          python predict_expected_counts.py
