name: predict-daily

on:
  schedule:
    - cron: "0 23 * * *"      # 매일 08:00 KST (UTC 23:00)
    # - cron: "30 23 * * *"   # (선택) 매일 08:30 KST 백업 실행
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      SHEET_ID: ${{ secrets.SHEET_ID }}
      SA_PATH:  ${{ github.workspace }}/sa.json
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth pandas numpy holidays

     - name: Write service account key (plain secret → file)
  shell: bash
  run: |
    # 멀티라인 시크릿을 내용 그대로 파일로 저장 (변수 치환/확장 방지용 'EOF')
    cat > "${SA_PATH}" << 'EOF'
${{ secrets.GDRIVE_SA_JSON }}
EOF

    # ✅ JSON 유효성 검사 (내용은 출력하지 않음)
    python - <<'PY'
import json, os
p = os.environ.get("SA_PATH","sa.json")
json.load(open(p,"r"))
print("✅ Service account JSON valid:", p, "size:", os.path.getsize(p), "bytes")
PY


      ㅍ
